# Generated by Django 4.1.7 on 2023-03-23 11:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ItemType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sales_channel",
                    models.CharField(
                        choices=[("ONLINE", "ONLINE"), ("OFFLINE", "OFFLINE")],
                        max_length=10,
                    ),
                ),
                (
                    "order_priority",
                    models.CharField(
                        choices=[("H", "H"), ("M", "M"), ("L", "L"), ("C", "C")],
                        max_length=10,
                    ),
                ),
                ("order_date", models.DateField()),
                ("order_id", models.IntegerField()),
                ("ship_date", models.DateField()),
                ("units_sold", models.IntegerField()),
                ("unit_price", models.FloatField()),
                ("unit_cost", models.FloatField()),
                ("total_revenue", models.FloatField()),
                ("total_cost", models.FloatField()),
                ("total_profit", models.FloatField()),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.country"
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.itemtype"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.region"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
